#!/usr/bin/env python
"""
author:  tfwroble@gmail.com
website: github.com/tfwio
license: free as in whistle.  use at own risk.

print git revision and date information

"""

import datetime
import os
from subprocess import Popen, PIPE

startpath = os.curdir
repository_path = os.path.join(startpath, 'smfio')

print_tree_fmt = '{}\n- revision: {}\n- count:    {}\n- date:     {}'


sha_length = 7

def cmd(*args, show_err=False):
  proc = Popen(args, stdout=PIPE)
  sout, serr = proc.communicate()
  if serr != None and show_err:
    print(serr)
  return sout.decode('utf-8')


def sha(branch='HEAD', show_err=False):
  result = cmd('git', 'show-ref', show_err=show_err)
  mhash = None # print('wha?: {}'.format(result))
  for row in result.split('\n'):
    if row.find(branch) != -1:
      mhash = row.split()[0]
      break
  return mhash


def read(target_file):
  with open(target_file, "w") as text:
    output = text.read()
  return output


def write(data, target_file):
  with open(target_file, "w") as text:
    text.write()
  return


def tree(branch='HEAD', date_only=True, show_err=False):
  mhash  = sha(branch)
  mcount = cmd('git', 'rev-list', '--count', mhash, show_err=show_err).strip()
  mdate  = cmd('git', 'show', '-s', r'--format=%ci', mhash, show_err=show_err).strip()
  return (
    mhash,
    mcount,
    mdate.split(' ')[0].replace('-','') if date_only==True else mdate
  )

def print_tree(name, branch='HEAD', date_only=True, show_err=False):
  mhash, mcount, mdate = tree(branch, show_err)
  print(print_tree_fmt.format(name, mhash, mcount, mdate))

def main():
  os.chdir(repository_path)
  print("\ntoday: {}\n".format(datetime.date.today().strftime('%Y%m%d')))
  print_tree('0.1.1',      'refs/tags/0.1.1')
  print_tree('smfio',      'refs/remotes/origin/HEAD')
  print_tree('smfio.view', 'refs/remotes/origin/smfio.view')
  os.chdir(startpath)

main()
