#!/usr/bin/env python
# https://stackoverflow.com/questions/311627/how-to-print-date-in-a-regular-format-in-python#311655
# https://stackoverflow.com/questions/5214578/python-print-string-to-text-file#5214587

import datetime
from subprocess import Popen, PIPE
import sys

def go():
  target_file = "./.src/Properties/AssemblyInfo.cs"
  bob = r'''
  using System;
  using System.Reflection;
  using System.Runtime.InteropServices;

  [assembly: AssemblyTitle("FFchap")]
  [assembly: AssemblyDescription("FFmpeg Chapter Utility\n{}\nwritten in CSharp\nTarget: DOTNET Framework v3.5")]
  [assembly: AssemblyCompany("tfwio")]
  [assembly: AssemblyProduct("FFchap")]
  [assembly: AssemblyCopyright("Copyright 2018")]
  [assembly: AssemblyCulture("")]

  [assembly: ComVisible(false)]
  [assembly: AssemblyVersion("0.0.0.1")]
  '''

  proc = Popen(['git', 'show-ref'], stdout=PIPE)
  stdout, _ = proc.communicate()
  result = stdout.decode('utf-8')
  
  for row in result.split('\n'):
    if row.find('HEAD') != -1:
      hash = row.split()[0]
      break

  today = datetime.date.today().strftime('%Y%m%d')
  gitsha = hash[0:9]
  output = bob.format('{} r:{}'.format(today, gitsha))

  # to target-file
  with open(target_file, "w") as text:
    text.write(output)
  # print to stdout
  sys.stdout.write(output+'\n')

go()
